language: android
android:
  components:
    - tools
    - platform-tools

    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

script:
    - ./gradlew testDebugUnitTest assembleDebug
